spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/instagram
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.default_batch_fetch_size: 10
      hibernate:
  #      show_sql: true
        format_sql: true
  profiles:
    active: local

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace